### ISSUE TITLE
Serpent don't include the license file

### ISSUE THREAD

**Issue by puntogil** [irmen/Serpent#11]
Not available LICENSE file in source directory structure
Please. Added license and copyright notice.
the fedora pakaging guideline is very strictly precise about this problem
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Text
thanks
regards

**Comment by irmen** [comment]
I see. That's easily solvable, I'll do it like with Pyro4.
