### ISSUE TITLE
make the .net library targeting a .NET standard version so it works on .net core too

### ISSUE THREAD

**Issue by irmen** [irmen/Serpent#17]

**Comment by ststeiger** [comment]
Mobius depends on this libary. 
If it isn't .net core ready, then Mobius can't be ported to .NET Core. 
https://github.com/Microsoft/Mobius
When Mobius can't be ported to .NET Core, Apache Spark-SQL can't be used in .NET Core.

**Comment by irmen** [comment]
@ststeiger can you perhaps help me with this? I have no experience with .Net Core.

**Comment by irmen** [comment]
Actually, I think we should focus on the .NET Standard to target...  https://docs.microsoft.com/en-us/dotnet/standard/net-standard  
Target should likely be .NET STandard v1.1 or v1.2

**Comment by irmen** [comment]
Hm, Jetbrains Rider which works on Linux, creates Dotnet Standard 2.0 solutions when working with a .NET Core project.  I guess we should target that.

**Comment by ststeiger** [comment]
@irmen: Agree. 
Seems to be the most reasonable target at the moment. 
Lower will die out anyway, sooner or later. 
And if anybody needs to backport, they can.

**Comment by irmen** [comment]
migrated to dotnet core solution, it compiles but a bunch of unit tests still fail.

**Comment by irmen** [comment]
Using xunit as test framework now, it works better, all tests pass now.  New nugget built and published successfully.
@ststeiger can you perhaps have a look at it to see if the new release works for you as well? (1.20, it should be up on nuget.org shortly)
