### ISSUE TITLE
Python + Serpent: float serialization accuracy

### ISSUE THREAD

**Issue by brubbel** [irmen/Serpent#19]
Hi,
When using Pyro4 with the default serpent serializer, I noticed that floats at the receiver side have a reduced 12-digit accuracy. For example:
```
SERPENT: 
1482514078.55
Original
1482514078.546359
```
It seems that in ser_builtins_float in serpent.py, a float is converted as follows:
`out.append(str(float_obj).encode("ascii"))`
while for full accuracy it should be like:
`out.append("{:f}".format(float_obj).encode("ascii"))`

Thanks for checking.

Edit:
> Python versions prior to 3.2 use 12 digits for the whole number when using str().
http://stackoverflow.com/questions/20586011/python-precision-in-string-formatting-with-float-numbers

**Comment by irmen** [comment]
Oh wow, that is a nasty bug, I think I've overlooked it because it doesn't occur on recent python versions.  Looks like the format call or repr() might indeed avoid the issue. I'll try to have a fix real soon because this is data loss 😢

**Comment by irmen** [comment]
problems also are present in java and .net implementations... 🙁

**Comment by irmen** [comment]
.. actually no, java and .net don't exhibit the floating point precision error. They do have a different issue with parsing certain complex numbers correctly, see issue #21

**Comment by irmen** [comment]
Note that this fix resulted in new Pyrolite and new Pyro4 releases as well, to require this new serpent library as a minimum.

**Comment by brubbel** [comment]
:+1: Checking it out now...

**Comment by brubbel** [comment]
Have tried new version of Pyro via PIP -> solved. Thanks!
