### ISSUE TITLE
Serializing properties

### ISSUE THREAD

**Issue by pevogam** [irmen/Serpent#28]
Hi,

Is there a way to make sure serpent serializes properties as well by default? Some of the proxy objects returned by remote calls I use have properties resulting in an error like

    TypeError: don't know how to serialize class <type 'property'>

I would prefer to avoid adapter classes but I don't know if this is possible.

Thanks!

**Comment by pevogam** [comment]
Using Pyro4.Proxy objects is actually a pretty good solution that closes my case here. On the side: the type error message would be clearer if it also contained the name of the serialized object in addition to its type. Thanks again!

**Comment by irmen** [comment]
Can you show some code that produced the typeerror you got?

**Comment by pevogam** [comment]
The code is too distributed but calls to remote objects simply return an object of this form

```python
class Result(object):
    def __init__(self, x, y):
        self._x, self._y = x, y

    def get_x(self):
        return self._x
    def set_x(self, value):
        self._x = value
    x = property(fget=get_x, fset=set_x)

    def get_y(self):
        return self._y
    def set_y(self, value):
        self._y = value
    y = property(fget=get_y, fset=set_y)
```

which when serialized by serpent raises the exception after recursing to *x* or *y*. Anyway, I have closed the issue but thanks for any opinion you have about the possibility of avoiding any serialization specific methods to the above object.

**Comment by irmen** [comment]
@pevogam you can simplify that code a little by using the ``@property`` decorator, but that doesn't change the fact that it works just fine:
```
irmen@debian:~$ cat testprop.py 
import serpent

class Result(object):
    def __init__(self, x, y):
        self._x, self._y = x, y

    def get_x(self):
        return self._x
    def set_x(self, value):
        self._x = value
    x = property(fget=get_x, fset=set_x)

    def get_y(self):
        return self._y
    def set_y(self, value):
        self._y = value
    y = property(fget=get_y, fset=set_y)

result = Result(10, 99)
ser = serpent.dumps(result)
print("SERIALIZED:", ser)
data = serpent.loads(ser)
print("DESERIALIZED:", data)

irmen@debian:~$ python3 testprop.py 
SERIALIZED: b"# serpent utf-8 python3.2\n{'__class__':'Result','_x':10,'_y':99}"
DESERIALIZED: {'_y': 99, '_x': 10, '__class__': 'Result'}
irmen@debian:~$ 
```

I really don't understand where your initial problems are coming from. I suspect you're doing something wrong, something else than you appear to think

**Comment by pevogam** [comment]
Interesting! Yes, I would prefer the property definitions without the decorator but it surprises me that you say it works. Could there be some cases of properties that won't work? Are you using the serpent module from the most current master? I will investigate again and write back when I have more results, knowing what you wrote above.

**Comment by irmen** [comment]
I used the current released version, 1.23.

Now, if I make a deliberate typo, where I'm trying to serialize the *actual class itself, rather than  an object of that type*,  I get an error that looks like yours:
```
serpent.dumps(Result)

[...]
TypeError: don't know how to serialize class <class 'property'>. Give it vars() or an appropriate __getstate__
```

It looks like your original error might be caused by a simple typo?

**Comment by pevogam** [comment]
Oh I see. As I said the code is really distributed and I do have (intentionally) class attributes on a few places. What I didn't know is that class serialization is not supported. My source of documentation was the python module docstring which explained that set literals are not supported and a few tricks related to other python versions. The last comment made everything clear, thanks a lot.

**Comment by irmen** [comment]
The docstring is fine, there's not much documentation elsewhere. The most important line in the docs related to your problem is probably this one:

> all other types --> dict with the __getstate__ or vars() of the object

Which basically means that if Serpent encounters an object of a type that doesn't fall in any of the other categories, it does this last resort behavior. Not all types support this last resort though hence Serpent is then giving up and suggesting that you "Give it vars() or an appropriate __getstate__".
Another solution is to not feed such types to Serpent in the first place, and try dealing with more basic types for serialization. Or add custom serialization rules using Serpent's ``register_class`` function.
