### ISSUE TITLE
Test files in sdist archive mssing

### ISSUE THREAD

**Issue by scarabeusiv** [irmen/Serpent#32]
Could you please add unittests to sdist archive on pypi? Distributions try to execute tests on the package to verify the reverse dependencies didn't break it. Without tests python packages are basically just `cp target destination` and with that we can't be sure if it really at least basically works.

**Comment by irmen** [comment]
How does a distribution know what tests to run?

**Comment by scarabeusiv** [comment]
We usually execute 'python setup.py test' or whatever is present in the travis of such project to validate sanity. In this case we would just execute the tests like you here in .travis.yml.

**Comment by scarabeusiv** [comment]
And when I tried to just ship the git tarball the tests worked, so when you release new sdist tarball I can let you know if it works, but based on the change above it should work :)
