### ISSUE TITLE
ValueError: Couldn't import 'kombu.transport.pyro:Transport': invalid literal for int() with base 10: 'dev0

### ISSUE THREAD

**Issue by coreycb** [irmen/Serpent#35]
This is already fixed in master, however I don't see that a new version of serpent has been released since 1.30.0. We have some code that uses serpent and is failing on import with:

```
    try:
        import serpent
        if '-' in serpent.__version__:
            ver = serpent.__version__.split('-', 1)[0]
        else:
            ver = serpent.__version__
>       ver = tuple(map(int, ver.split(".")))
E       ValueError: Couldn't import 'kombu.transport.pyro:Transport': invalid literal for int() with base 10: 'dev0'
```

This is due to:
`serpent.py:__version__ = "1.30.dev0"`

As a work-around I'm going to patch the ubuntu package with:
`serpent.py:__version__ = "1.30"`

**Comment by irmen** [comment]
Where is that first code piece coming from?

Also, there *is* a newer serpent release available,   1.30.2 is on pypi. I am not sure what your remark about the version is referring to?

**Comment by coreycb** [comment]
The debian pacakge picks up releases from:
`https://github.com/irmen/Serpent/tags .*/archive/serpent-v?([\d\.]+)\..*`

pypi isn't generally a supported package format for distros whereas debian packages are (ie. apt install).
The import is coming from pyro4, but it's easily reproducible without it:

```
$ python3
Python 3.7.6 (default, Jan 16 2020, 18:23:42) 
[GCC 9.2.1 20200110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import serpent
>>> ver = serpent.__version__
>>> ver = tuple(map(int, ver.split(".")))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: invalid literal for int() with base 10: 'dev0'
>>> 
```

I think if a new release artifacts were available on git then this could be closed since it's fixed in new point releases.

**Comment by irmen** [comment]
I see! I didn't know debian packages are looking at the git tags.
I'll fix the version parsing in Pyro and tag a release in Git.

**Comment by irmen** [comment]
done, thanks again for the heads up

**Comment by coreycb** [comment]
Thanks irmen!
