### ISSUE TITLE
consider using bytes literal for bytes serialization instead of base64

### ISSUE THREAD

**Issue by eudoxos** [irmen/Serpent#38]
I have to hand-check in many places (when using Pyro5 w/ Serpent) where bytes are supposed to be returned whether the object is bytes or dict, and unpack it. While I understand that not all values have literal representation and must be handled specially (such as NaNs), bytes objects do have literal representation: e.g. `b'\x00\x01BDFSD'`. This could be used to recover bytes object automatically in `ast.literal_eval`. I understand that the length might be bigger than base64 in some cases (and smaller in others). As a user, I would much appreciate the ease of use, though.

**Comment by irmen** [comment]
You can use the ``serpent.tobytes()`` utility function to ease the pain a little.

I'll have to investigate what the impact would be of a change to bytes literal representation, but it's an interesting idea.

**Comment by irmen** [comment]
Implemented switch in Serpent to select bytes repr for serialization (default=no)
Also added SERPENT_BYTES_REPR config item in Pyro5 to enable this (default=off), this will be part of the next release but you can try it out already in the master branch of Pyro5 as of now.
