### ISSUE TITLE
new release: 1.40

### ISSUE THREAD

**Issue by xyproto** [irmen/Serpent#39]
Hi,

The version number for Serpent on PyPI is 1.40, while the latest tag here is 1.30.2.

Please create a new git tag. This makes it easier for me to upgrade the `python-serpent` package in Arch Linux.

Best regards,
Alexander F. Rødseth

**Comment by irmen** [comment]
Yep I will certainly do this, once the Java and C# versions have been finalized as well!  
(these need to be upgraded to 1.40 too)

**Comment by irmen** [comment]
done!
