### ISSUE TITLE
Dictionary size changed during iteration

### ISSUE THREAD

**Issue by hangongithub** [irmen/Serpent#5]
Every now and then, when calling Serpent (via Pyro), I get "Dictionary size changed during iteration" exception.

It comes from line 238 to 241 (_serialize method) in serpent.py (version 1.7):

        for clazz in _special_classes_registry:
            if isinstance(obj, clazz):
                _special_classes_registry[clazz](obj, self, out, level)
                return

It seems that if the if-block returns true, the exception will get thrown.  I don't know why it doesn't always happen.

**Comment by hangongithub** [comment]
Actually, my mistake, it shouldn't throw an exception since you're not modifying it.  You're just calling it.  

I think what might be happening is either unregister_class or register_class gets called while it is iterating.  So there might be a race condition there.

**Comment by irmen** [comment]
The serializer is not thread-safe. (See the comments in the code, I've added them to the readme now as well). If you're using it in a multi threaded scenario, provide your own thread synchronization.

**Comment by irmen** [comment]
In all honesty, you should probably never be modifying a dict (or other data structure) from thread A when it is also used in thread B, unless you have a lock in place. It's just that you now experienced one problem from within Pyro, but this practice can break your code in any place...

**Comment by irmen** [comment]
hmm wait, I could perhaps make it more robust anyway because it is the unregister_class/register_class methods from serpent itself that you're calling.  Maybe I can simply change the way serpent iterates over its internal dict and thus prevent this particular kind of race condition. Will investigate.

**Comment by irmen** [comment]
Pyro 4.32 (just released) has an updated dependency on the new Serpent library 1.8 where this is fixed.  You can either upgrade serpent separately or upgrade Pyro4 and you'll get it automatically
